/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\Kaoticode.glb --transform 
Files: .\Kaoticode.glb [588.77KB] > C:\discord\kaoticode\kaoticode-next\public\Kaoticode-transformed.glb [46.4KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF, Edges, Outlines, useTexture, Image, Billboard } from '@react-three/drei'
import { MeshTransmissionMaterial } from '@react-three/drei'
import { useControls } from 'leva'
import * as THREE from 'three'
export function KaotiCode(props) {
  const texture = useTexture('/images/code2.jpg')

  const config = useControls({

    meshPhysicalMaterial: false,
    transmissionSampler: true,
    backside: true,
    backsideThickness: { value: 3.5, min: 0, max: 10, step: 0.01 },


    iridescence: { value: 0, min: 0, max: 1 },
    iridescenceIOR: { value: 1.5, min: 1, max: 5, step: 0.01 },
    anisotropicBlur: { value: 0, min: 0, max: 1 },
    envMapIntensity: { value: 0.06, min: 0, max: 1 },
    samples: { value: 10, min: 1, max: 32, step: 1 },
    resolution: { value: 2048, min: 256, max: 2048, step: 256 },
    transmission: { value: 1, min: 0, max: 1 },
    roughness: { value: 0.0, min: 0, max: 1, step: 0.01 },
    thickness: { value: 3.5, min: 0, max: 10, step: 0.01 },
    ior: { value: 1.5, min: 1, max: 5, step: 0.01 },
    chromaticAberration: { value: 0.06, min: 0, max: 1 },
    anisotropy: { value: 0.1, min: 0, max: 1, step: 0.01 },
    distortion: { value: 0.05, min: 0, max: 1, step: 0.01 },
    distortionScale: { value: 0.4, min: 0.01, max: 1, step: 0.01 },
    temporalDistortion: { value: 0.5, min: 0, max: 1, step: 0.01 },
    clearcoat: { value: 1, min: 0, max: 1 },
    attenuationDistance: { value: 0.5, min: 0, max: 10, step: 0.01 },
    attenuationColor: '#ffffff',
    color: '#ffffff',

    bg: '#839681'
  })
  const { nodes, materials } = useGLTF('/Kaoticode-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <Billboard
        follow={true}
        lockX={false}
        lockY={false}
        lockZ={false} // Lock the rotation on the z axis (default=false)
      >
        <Image url="/images/code.jpg" alt="code" position={[0, 0, -2]} scale={[7, 4, 1]} />
      </Billboard>
      <mesh geometry={nodes.Text.geometry}
        rotation={[Math.PI / 2, 0, 0]} >

        {config.meshPhysicalMaterial ? <meshPhysicalMaterial metalness={0} transmission={1} ior={1.5} clearcoat={1} /> : <MeshTransmissionMaterial background={new THREE.Color(config.bg)} {...config} />}
      </mesh>
    </group>
  )
}

useGLTF.preload('/Kaoticode-transformed.glb')
